POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik11c2tPeDY2NiIsImlkIjoiNWVjMDczYWVkNjYyNmY5YTAxNDZlYTIxIiwiaWF0IjoxNTg5NjcwOTI2fQ.cElpldOCvBcwDZjF6TK03f05Ly9DDqMD90bCshKTVyU

{
    "content": "Beauty is in the eye of the beholder",
    "important": false
}